unique_ids:
  assets:
    standard-page.html: 5GVMAYJ2FZ67C5HWIZ3UZX4O5AJDONKR
    theme.css: ZVXKDPWIZCYR347TWGJXHHNBZFLF72AG
  forms:
    Form1: VFZML4KZ5TR7X5VX34ESKPEWEYZZ2L3C
  modules: {}
  scripts: {}
  server_modules:
    server_module: Q57WLR4FXIZFDZ3CKCZOI37RZJJEOMKO
